# Generated by Django 3.1.4 on 2020-12-10 01:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Titulo', max_length=200, validators=[django.core.validators.MaxLengthValidator(500, message='Nome grande demais.')])),
                ('dataPublicacao', models.DateField(help_text='Data de Publicação', null=True)),
                ('autor', models.CharField(help_text='Nome do Autor', max_length=100, validators=[django.core.validators.MaxLengthValidator(500, message='Nome grande demais.')])),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço por exemplar', max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='Preço deve ser maior que zero.')])),
                ('quantidadeExemplares', models.IntegerField(help_text='Qtd de Exemplares', validators=[django.core.validators.MinValueValidator(0, message='Quantidade deve ser maior que zero.')], verbose_name='Numero de Exemplares')),
                ('Funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
