# Generated by Django 3.1.3 on 2020-12-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Titulo', max_length=50)),
                ('dataPublicacao', models.DateField(help_text='Data de Publicação', null=True)),
                ('autor', models.CharField(help_text='Nome do Autor', max_length=30)),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço por exemplar', max_digits=5)),
                ('quantidadeExemplares', models.IntegerField(help_text='Qtd de Exemplares')),
            ],
        ),
    ]
