# Generated by Django 3.1.3 on 2020-12-03 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_livro_ehfuncionario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='ehFuncionario',
            new_name='Funcionario',
        ),
    ]
