# Generated by Django 3.1.3 on 2020-12-03 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_auto_20201203_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='Funcionario',
        ),
    ]
